{% set name = "unumpy" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight-Labs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 98b3be46548e941f0d00bacf377835a3471e3deb1630d1fefe642d8b53232a3c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - uarray ==0.6

test:
  imports:
    - unumpy

about:
  home: http://github.com/Quansight-Labs/unumpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A backend-dispatchable version of NumPy'
  description: |
    `unumpy` is a backend-dispatchable version of NumPy.
  doc_url: http://unumpy.readthedocs.io/
  dev_url: https://github.com/Quansight-Labs/unumpy

extra:
  recipe-maintainers:
    - hameerabbasi
