{% set name = "unumpy" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight-Labs/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 9439b19a04275b97ef9cdc5a97ddd00939b022ad4685d366eba5ea1a511dc2c8

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - uarray

test:
  imports:
    - unumpy

about:
  home: http://github.com/Quansight-Labs/unumpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A backend-dispatchable version of NumPy'
  description: |
    `unumpy` is a backend-dispatchable version of NumPy.
  doc_url: http://unumpy.readthedocs.io/
  dev_url: https://github.com/Quansight-Labs/unumpy

extra:
  recipe-maintainers:
    - hameerabbasi
