travis:
  secure:
    BINSTAR_TOKEN: SMocQy0Kj+DrF9v4ziGFbwU2EgU64Pk8w6fNHp6D1kcrBNQedzkGzsfbCyO9wHPiiziAPla/klXyyXkYo5EvP5iflSWr313/1Mj0BtwbSaEMjcYtFW1TV75SlbBB/oZUOfQJ31NkxqQyE5YrQFICcTl0QBMrlxq+NUmjXMLE80Pi8DWNObahqUlepuVVdYvc9Y3FuesJ9ZTt3xowDcOAWumDhU0hvFbH9kNYiKj886SB4NKO3r47F8G2IiURDfeml0xUn8Zw0Q3F0to3uVjKcrDBY17CdkS6dY++V4YzNLWlvHT+nNK22h5u6jytJMk1GwFNxMck7VuAED7iQ2erujtl8w8Qswj0Wc2cc3+90Kl81RHaczweGdn8dd42t1p2acsEiUAP9ouInTmFWTezrynI1N2HmMOyljM9Kh0v6qN7KI6g57cOrLzHXw4jJ42TYI10b7iHyLeDYcfdwfehGoKm2A31YQJJbaoV215EHbKdoNIRq4nUKBBw7m1iIXiWUytZTgL5cwNZBuWmWkjP4yfyK1QsvN49YTZYt71Fwa+5+v0qaiL8U16X0Q6H1vv4SJB7NycYgew06yYSfd0Xw4Vn9irt79rJiXtNRIYKSVtbQ/0kmYcArDXz2GP5RFC6ROMqrgCnm06gpxPC+FNOByX6LSxxmd2fWykvTCJFHQg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
