travis:
  secure:
    BINSTAR_TOKEN: j5otPmcTBYNyhpzEdZjoKKAS309cO7eTcXjNgIi8z5gWDzwLzqFZdknqswn7DfEhS+lCvuKRTg8QLlZFquhWautO76nkVa2pWZnlN1+LXl72HAq3WefSFiF7jNX6UXyqqCI3nTjrueAvVtM8avtlCCrWUUggEWliysjHKkmfJpr79uKijncYqPlkvyVnvDZ457PV43aXfSVNish60DIiJWH3ZWCt8ZORolWL0DKWOj6InprY4fXnL1bpuOKopDOxazTJXA8n7b7hIZmkj0bkQ4zDrfA/d9YC/MH2SROMdw/Ld1Wv+JePVfvOU4MvBX3M2+bjCep9BsRzTmX4ARnupLU+bg2gq8I8YK7Te1oJr1eBjMYrrFuGi/5k/mMviyRFwhJGJ5am6V+BRxHw8fxvuz93Fx3utSwKKcqWHkwxgO9SLTuR/rS9gWUtHwE4lngqOgZDmiD8Uz81I7SykEuMQ/mpLlZqK+VPTUTv+eLbHx6lJQDEtV7usmVfXcy7IKS4c5AyYquM/d4Pqpa6UO29Q3q15gNFw/Fj4KCxtK6IqID8UmYfZGWNBoYVAdw9hyqNuX03fYR89Bx/il1DCVCriYm7iyS7+hNVizEAtriUIVTSFfYZ/YUpyMh15Tgl79vu3b/mirGh5QljbievFXopKTIREl33K2VMdhNqAptRw24=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
